### ISSUE TITLE
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object

### ISSUE THREAD

**Issue by ghost** [cybozu/passh#1]
Hi,

When i tried passh, it worked, but the Python code raised an exception:

```
$ python __init__.py ach 'ls /'
[ach] bin
[ach] boot
[ach] dev
[ach] etc
[ach] home
[ach] lib
[ach] lib64
[ach] lost+found
[ach] media
[ach] mnt
[ach] opt
[ach] proc
[ach] root
[ach] run
[ach] sbin
[ach] srv
[ach] sys
[ach] tmp
[ach] usr
[ach] var
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 381, in __del__
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 58, in close
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 139, in remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

Any idea why this exception was raised?

Have a nice day.

Cheers,
Asher256

**Comment by ymmt2005** [comment]
Thank you for the report.  I will take a look in a week or so.

**Comment by ghost** [comment]
Thank you Yamamoto! Let me know. I'll try it again to confirm if the bug was fixed on my side.

**Comment by ymmt2005** [comment]
This happens since Python 3.4.3 when they changed asyncio someway.
https://bugs.python.org/issue23548

A design issue difficult for libraries like passh...

**Comment by ymmt2005** [comment]
Asyncio programs are responsible to close the event loop by themselves.
For non-asyncio programs, passh should create and use a dedicated event loop
by [`asyncio.new_event_loop`](https://docs.python.org/3/library/asyncio-eventloops.html#asyncio.new_event_loop)?

**Comment by ymmt2005** [comment]
@Asher256 
Could you try the new version?

**Comment by ghost** [comment]
I'm going to try it and let you know.

**Comment by ghost** [comment]
It works Yamamoto ! Thank you for the fix !

**Comment by ymmt2005** [comment]
:+1:
